apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/khartson/project-k8s-gitops
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
      include: "*.yaml"
      exclude: "root/*"
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd 
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true
  