apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        fsGroupChangePolicy: "OnRootMismatch"
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: discord-bot
          image: ghcr.io/khartson/beerbot:latest
          ports:
            - containerPort: 8080
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: BOT_TOKEN
            - name: FILE_SOURCE
              value: "upload"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: bot-data
              mountPath: /app/data
      volumes:
        - name: bot-data
          persistentVolumeClaim:
            claimName: discord-bot-data-pvc
