apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discord-bot-data-pvc
  namespace: discord-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
