---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: discord-bot
spec:
  encryptedData:
    .dockerconfigjson: AgA/uol8sBiRe2KVv1pY7WO3ixfLidff6Ws7crdk/4BZFZsdZw/WlsjkZ542WJ+j8mBo9jN9tv+Lh+MLI7/KGZnA3/BE3lneA1A/+AOiQW2GiKgEXS+NUhoC5e76H62ZzSMtQbj0aDZ8BztjagGDYmhQdM68qq0EIVRJgCC9/SahTxcXOYKUJfHlT60btx+qjqF3W9dF5t7FulkUlzR0S3UrFVnVWJp674k2aBk3uyYt3ImCHz5MjCEmUF29iTCHPkMbuzvX+CwmLAememjsCNzw6Qwa6czXRmudyBnWDp0rOPZaUZc0jhI4nb/OYyNNCO0HChExXvyIchOW1nW+Zvn1bMpzq3bt1NZdlMe2jvbn1tB9a42C+8epSQP5G0gZ9Sv+lKNsgZJr4B3Tsq7RJLO5N/7HUdw6wd4kH4yFjCKckprSwJPkt6g+FZwjcm/zsXlNq265VR7m6RUtjQaTs7WQvCbh5+w8iwHL+dc2PzEaUJCJkAV8diRWDl5K2HlkZhHZPrvb05ecSkPBXnE2J+LeXAWy8kIuajNK+hKC3YML5zQzFvs9Oa4aOvhCI+BF7OuWSBhfxOJ4J54Kt0ARbdM3LiuvoSMz4G/CbtZpsDGZ5CXTm8ewV+iE8ftxXYmdDaPYuLzFVcaZQ6vneE4NH+Nfjn+9NTT+YYVcxAe4yuX3lOuA4M7gMX2GgEUkjXILekL6kiA7f/HTqxpaXxe5Qb/QhAyeB3HgZDfflBXfm8FQFGgGF370xaGHnxipmwWAVwTa3bLUr+0oM82CmtgP4VkMA4YY5wS3/DH12xVHgwF8DIl1aan28NMAysXkKYg7gujxy4wuLT1UGw3racizpy9Yv42EGOlAdKli/zP091BnHqzDfoGypxe5Uz7hGQx+b0wLQcT3+ITHrj5ZgxwFrTt1lzg7YxZQBoGcqOrl1md8rNY=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: discord-bot
    type: kubernetes.io/dockerconfigjson
