apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.20.1
    helm:
      values: |
        cgroup:
          autoMount:
            enabled: false
          hostRoot: /sys/fs/cgroup
        ipam:
          mode: kubernetes
        k8sServiceHost: 10.0.1.50
        k8sServicePort: 6443
        mtu: 1450
        routingMode: native
        autoDirectNodeRouting: true
        ipv4NativeRoutingCIDR: "10.0.0.0/16"
        securityContext:
          capabilities:
            ciliumAgent:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
