apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discord-bot-ingress
  namespace: discord-bot
spec:
  ingressClassName: tailscale
  rules:
    - host: discord-bot
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: discord-bot-service
                port:
                  number: 8080
  tls:
    - hosts:
        - discord-bot
